server:
  port: 8001

accessFile:
  portrait:
    resourceHandler: /moonker/portrait/** #匹配需要拦截的URL
    location: E:/moonkerwd/moonker/portrait/  #本地文件夹

spring:
  application:
    name: user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/blog_graduate?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: QweAsdZxc123
    druid:
      validation-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fred.entities


#eureka:
#  client:
#    #是否将自己注册进EurekaServer
#    register-with-eureka: true
#    #是否从EurekaServer抓取已有的注册信息,默认为true。 在集群情况下使用true 配合ribbon负载均衡
#    fetch-registry: false
#    service-url:
#      #      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: user8001
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2

